### ISSUE TITLE
Objects in need of creation

### ISSUE THREAD

**Issue by DarixRexus** [RobustTeam/tg-ashcloud#27]
obj/structure/chair/wood - Remnants
obj/structure/simple_bunker/bunker - Remnants
obj/structure/rack - Remnants
obj/structure/car - Remnants
obj/structure/simple_door/metal/barred - Remnants
obj/structure/barricade/bars - Remnants
obj/machinery/door/poddoor/gate - Remnants
obj/structure/simple_door/metal/store - Remnants
obj/structure/campfire/stove - Remnants
obj/structure/table/wood/settler - Remnants
obj/structure/wreck/bus/rusted - Remnants
obj/structure/billboard/ritas - Remnants
obj/item/flag/ncr - Remnants
obj/item/flag/legion
obj/structure/sign/poster/ncr/democracy
obj/structure/sign/poster/ncr/irradiated_food
obj/structure/sign/poster/ncr/loaded
obj/structure/sign/poster/ncr/keep_to_myself
obj/structure/sign/poster/prewar
obj/structure/decoration/rag

**Comment by Dr-Oreo** [comment]
obj/effect/decal/marking - Remnants or BD
obj/effect/decal/waste - Remnants or BD
obj/structure/fluff/rails - Remnants or BD
obj/structure/tires - Remnants or BD

(Turfs that aren't already in)
turf/open/indestructible/ground/outside/grass_s - Remnants
turf/open/indestructible/ground/outside/dirt_s - Remnants
turf/open/indestructible/ground/outside/ruins - Remnants or BD

**Comment by Koshenko** [comment]
Turfs heavily refactored and dependence on decals reduced.
