### ISSUE TITLE
Gotta port over the fucked up snow/wood floors.

### ISSUE THREAD

**Issue by ProfessorPopoff** [RobustTeam/tg-ashcloud#43]
Similar to the desert/ripped up wood flooring tile, The snowy counterpart has yet to be ported, yet.

**Comment by uomo91** [comment]
I've opted to just keep these out of the repo, they're not really needed.

**Comment by ProfessorPopoff** [comment]
> I've opted to just keep these out of the repo, they're not really needed.

But..
 But.... Fallout13 without destroyed floors...?

**Comment by uomo91** [comment]
> > I've opted to just keep these out of the repo, they're not really needed.
> 
> But..
> But.... Fallout13 without destroyed floors...?

There are still destroyed wooden floors and destroyed carpeted wooden floors, just none that show sand/snow underneath the framing. Unneeded and we'd end up having to make a variant for any kind of terrain we'd use in future maps (for instance, Dogtown may likely be set in a muddy place).

Not worth the overhead.

**Comment by LemonInTheDark** [comment]
*might* be able to work around it

**Comment by Koshenko** [comment]
Turfs heavily refactored.  Many old turfs have been cut.
