### ISSUE TITLE
Certain turf tiles once destroyed appear as desert turfs.

### ISSUE THREAD

**Issue by ProfessorPopoff** [RobustTeam/tg-ashcloud#48]
https://gyazo.com/f8833794a66ede5f8553ae9b85cfa7f5
https://gyazo.com/cc0589b323e1615c9947ba09afc8870d

/turf/open/floor/wood/f13/old

as do /turf/open/plasteel/f13/vault_floor

 becomes desert underneath once blown up completely

**Comment by ProfessorPopoff** [comment]
Similarly, /turf/open/floor/dirt turns into plating once destroyed.

**Comment by uomo91** [comment]
This appears to be resolved, now.

>/turf/open/floor/wood/f13/old
>
>as do /turf/open/plasteel/f13/vault_floor
>
>becomes desert underneath once blown up completely

Explosions that destroy plating now simply show the z-level below.

There are some other problems though, namely it leaving lattice and you being unable to walk over it.

**Comment by ProfessorPopoff** [comment]
Well. We didn't really want the ground to be able to get blown up entirely to dump into the cave area- Or even the megadungeon. That would make a shitton of problems on its own.

**Comment by uomo91** [comment]
The dungeon is a completely separate map and there is no way into it from the normal map aside from whatever you explicitly code in (probably an elevator) to access it.

I'm not sure how you can make a turf besides open space appear when an existing turf is destroyed, but I guess it might be possible.

**Comment by ProfessorPopoff** [comment]
Forgot briefly that the megadungeon was serperate, so void that. But yeah. Blowing holes in the ground would lead to some wacky loot rushing. Local prospector blows into a military dungeon's loot room with a single frag grenade.

**Comment by Koshenko** [comment]
New turf/map PR about to be merged.  No longer an issue.
